# Generated by Django 3.1.7 on 2021-03-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=255)),
                ('phone', models.IntegerField()),
                ('book_from', models.DateField()),
                ('book_till', models.DateField()),
                ('persons', models.IntegerField()),
                ('bed_type', models.CharField(max_length=100)),
            ],
        ),
    ]
