# Generated by Django 3.1.7 on 2021-04-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField()),
                ('bed_type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
